fix: downgrade interpax
v0.3.8 to, at least, v0.3.13 seem to have some problems, especially with their equinox dependency. This causes errors in interpolation of ragged arrays that look like this:

_EquinoxRuntimeError: A linear solver received non-finite (NaN or inf) input and cannot determine a
solution.

This means that you have a bug upstream of Lineax and should check the inputs to
`lineax.linear_solve` for non-finite values.